# SPDX-FileCopyrightText: Copyright © DUNE Project contributors, see file AUTHORS.md
# SPDX-License-Identifier: LicenseRef-GPL-2.0-only-with-DUNE-exception OR LGPL-3.0-or-later

# Dune module information file

Module: dune-functions
Version: 2.11-git
Maintainer: dune-functions@lists.dune-project.org
Python-Requires: scipy
Depends:  dune-localfunctions (>= 2.11) dune-grid (>= 2.11) dune-istl (>= 2.11) dune-uggrid (>= 2.11)
Suggests: dune-typetree (>= 2.11)
Whitespace-Hook: Yes
